The Next Web clone
Jarfsoft/Building-with-Responsive-Design pull request #1
Opened 2020-10-02 22:53 UTC by Jarfsoft

**HTML elements added:**

- Header
- Body
- Sections
- Footer

**CSS Styles added:**

- Responsive styles to mobile version
- Responsive styles to Ipad version
- Styles to Desktop version

2020-10-03 01:06 UTC, teekaytech requested changes
# Status: Changes Required :warning: :construction:

## Hi team :wave: 
**This project is looking great :clap:**
- Well composed README file :+1: 
- Descriptive PR title and summary :100: 
- Your linters are green :heavy_check_mark: 
- Nice implementation :tada: 

Overall, this is an awesome job and I'm impressed!. However, we do have some changes to make before the project can be approved (see comments below).

**[ REQUIRED CHANGES ]** 

_I will focus on responsiveness in this review as the main point of this project is to implement a Responsive Web Design._

**Medium version changes (768px - 1023px)** 
- [ ] The TNW logo seems to be overlapping on a nav item. Kindly fix this.

Source page:
![01:48:08](https://user-images.githubusercontent.com/26856491/94979433-82ff7380-051a-11eb-968d-308fa0970db6.png)

Your page:
![01:47:47](https://user-images.githubusercontent.com/26856491/94979438-88f55480-051a-11eb-8e9e-bf0e1beea781.png)

- [ ] The `Latest Funding` section aligns 3 articles per row (768px - 1023px).

Source page:
![01:55:14](https://user-images.githubusercontent.com/26856491/94979610-9f4fe000-051b-11eb-90b3-536c6d723450.png)

Your page:
![01:56:05](https://user-images.githubusercontent.com/26856491/94979614-a2e36700-051b-11eb-8e38-69eeb4824fcd.png)

**Small version changes (<= 767px)** 

- [ ] There seems to be a bug in the footer section. Check the images below:

Source page:
![02:02:01](https://user-images.githubusercontent.com/26856491/94979733-7e3bbf00-051c-11eb-8301-841e4bcfcd57.png)

Your page:
![02:01:52](https://user-images.githubusercontent.com/26856491/94979736-83007300-051c-11eb-9d3e-33f7c43d7134.png)


* **When you have made the specified changes, please submit another code review.**
* **If you feel like you need help or you have any question(s), I'm @taofeekolalere on slack**

Regards,
[Taofeek Olalere](https://github.com/teekaytech)
Happy Coding :technologist:

2020-10-03 01:06 UTC, teekaytech commented on README.md
> +- LinkedIn: [Mir Rawshan Ali](https://www.linkedin.com/in/mir-rawshan-ali-27b6a5198/)
Preview this page from GitHub and fix the formatting issues. 
- The authors should be separated by space.
- Fix the markdown formatting bugs.

[This](https://guides.github.com/features/mastering-markdown/) might help.

2020-10-03 01:06 UTC, teekaytech commented on README.md
> +- New York Times
I'm sure this is a copy/paste error because The Next Web has nothing to do with New York Times :smile:. Kindly fix it.

2020-10-03 01:06 UTC, teekaytech commented on assets/styles/style.css
> +}
There seems to be a lot of repeated rules here. Always keep your code DRY. Please group like rules together to ensure DRYness in these blocks and all other blocks where such is happening in your code.

![01:33:42](https://user-images.githubusercontent.com/26856491/94979042-81cd4700-0518-11eb-9cf2-9694edc64ead.png)


[This article](https://speckyboy.com/good-bad-css-practices/) might help in understanding CSS good practices.

2020-10-03 01:06 UTC, teekaytech commented on index.html
> +      <p><img class="footer-logo-img" src="https://cdn0.tnwcdn.com/wp-content/themes/cyberdelia/assets/img/tnw.svg" alt=""> © 2006–2020 The Next
The `alt` attribute value is missing. Kindly add it.

2020-10-03 08:08 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__I must say, you've done an amazing job so far. However, there are some changes that are required to be fixed before this project can be approved. Please check my points below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] You are still having some repeated rules in your CSS file. Please check my previous comment and refactor as appropriate.

![08:56:40](https://user-images.githubusercontent.com/26856491/94986404-6123e200-0556-11eb-96cf-4242ae21e9f5.png)

_**Note that this is one of the microverse specific requirements for this project. So it is important you refactor your CSS file.**_

![08:59:31](https://user-images.githubusercontent.com/26856491/94986448-ced00e00-0556-11eb-96cd-046f84270422.png)


**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-10-03 09:31 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

Hello @Jarfsoft and @sumon0002001, Great job! 👏  Both of you have done well on this project.
Let's make a few changes, and we will be done.

- [ ] Fix the HTML validation warnings/errors, use the [w3 Validator](https://validator.w3.org/)

- [ ] Add **.DS_Store** inside your assets folder to **.gitignore** file

- [ ] There is a stranded `head>` tag at the bottom of the page, I'm sure if you fix the HTML validation errors, it should fix it as well. 
![fo](https://user-images.githubusercontent.com/5264771/94987705-2a52c980-0560-11eb-86a9-5e19095b9abe.jpg)

- [ ] Like the Previous TSE said, you still have some repeated rules in your CSS file. No worries 😄 I have provided some hints below on your code to help you.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-10-03 09:31 UTC, acushlakoncept commented on assets/styles/style.css
> +}
If you notice there is a lot of repeated `linear-gradient(to top, rgba(0, 0, 0, 1), rgba(0, 0, 0, 0.4))`
One good way to overcome this is to use [CSS Variables](https://www.w3schools.com/css/css3_variables.asp). Example:

```
:root {
  --gradient: linear-gradient(to top, rgba(0, 0, 0, 1), rgba(0, 0, 0, 0.4));
}

/* use it like this */
.hf-img {
  background-image: var(--gradient), url(../images/hf.jpg);
}
```
Now, it becomes very easy to make one change to affect the rest.

2020-10-04 05:23 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Good job with the changes, team! 👍  I can see you put a lot of effort into them! 👏 
But we still to implement some changes before the project get approved 💪 

Please, check my comments below 👇  apply the changes and resubmit your project fo a new code review ⏩ 

Good luck with it! 😃 

## Changes

- Screens above 1024px:
   - hard fork, apps, gear.... sections, kindly fix the size of the image and the size of the text in the lastest section
original:
![Capture](https://user-images.githubusercontent.com/56809963/95007549-4e221800-0611-11eb-9b20-55b5cc6480c1.PNG)
Your project:
![Capture1](https://user-images.githubusercontent.com/56809963/95007560-62feab80-0611-11eb-9d66-f69b5e468918.PNG)
- Screens below 1024px:
   - in the latest fundings section the add info, get updates and see more links must be inline
   - Keep working on the images sizes in the hard fork, apps section
- Screen below 768px:
   - in the hard fork, apps... sections, kindly fix the image of the latest section
![Capture2](https://user-images.githubusercontent.com/56809963/95007635-ffc14900-0611-11eb-9ee8-f99a2c8be283.PNG)
   - Keep working on the images sizes in the hard fork, apps section

2020-10-04 07:17 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Great Job, Team!, awesome progress you've made 👏 
Let's make a few changes, and we will be done.

- [ ] You still have some HTML validation warnings/errors to fix, use the [w3 Validator](https://validator.w3.org/)

- [ ] You're yet to "kindly fix the image of the latest section" for screen below 768px as requested by the previous TSE
![latest](https://user-images.githubusercontent.com/5264771/95009375-8168a500-0619-11eb-9c3f-95976a6c0149.jpg)

Apply these changes and resubmit another code review request.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-10-04 07:57 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Hello again, team!
You are making progress! 👏 


But we still need to implement some changes 💪 
Check them below 👇 

## Changes
- You still have some HTML validation warnings/errors to fix, use the [w3 validator](https://validator.w3.org/)
- Screen below 768px, in the hard fork, apps... sections, kindly fix the image of the latest section
- Screens below 1024px, in the latest fundings section the add info, get updates and see more links must be inline
- In the whole page, in hard fork, apps, gear.... sections, kindly fix the size of the image and the size of the text in the lastest section

2020-10-04 10:07 UTC, teekaytech reviewed
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__I must say, you've done an amazing job so far. However, there are still some minor changes that are required to be fixed before this project can be approved. Please check my points below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] In the `Latest Fundings` section, when rendered for medium screen sizes (768px - 1024px), the `Add info`, `Get updates by email` and `See more` items are on the same line, but you have them on separate lines in your clone. Kindly fix it.

Source page:

Your clone:


- [ ] In the latest deals section, the old and new prices are both on the same line. Kindly put them on the same line on your clone.

Source page:
![10:59:09](https://user-images.githubusercontent.com/26856491/95012475-c8ae6000-0630-11eb-81f7-b41547606f09.png)

Your page:
![10:59:55](https://user-images.githubusercontent.com/26856491/95012477-cd731400-0630-11eb-8ef5-7d8f00161148.png)


**[ OPTIONAL CHANGES ]**

**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-10-04 11:32 UTC, teekaytech approved these changes
# Status: Approved :green_circle: 

### Congratulations team, this project has passed all the mandatory requirements. It is therefore approved :heavy_check_mark:

Again, congratulations :tada: You can merge to master.

Do not forget to fill the project completion form.

Good luck with your next task.

**I'm @taofeekolalere on slack.
Happy Coding :man_technologist:**

2020-10-04 11:34 UTC, merged